fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3.8
        args:
          - --profile
          - black
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10
        args:
          - --line-length=88
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        language_version: python3.8
        args:
          - --ignore=E203,E266,E501,W503,F403,F401,E402,F405,F541,E731,E722,F841,E711,E712
          - --max-line-length=88
          - --max-complexity=70
          - --select=B,C,E,F,W,T4,B9
